### ISSUE TITLE
2주차 퀴즈

### ISSUE THREAD

**Issue by pawoo0211** [java-pg-study/pg_platforms_study#107]
- [ ] 클래스의 속성을 감추는 접근 제어자는 [ ]이며 속성을 외부로 제공해야 할 때 사용하는 메서드의 접근 제어자는 [ ]이다.
- 44 Page 참고 바랍니다.
- [ ] 어떤 메서드들이 서브 클래스나 내부에서만 접근 가능해야 할 때 사용되는 접근 제어자는 [ ]과 [ ]이다.
- 44 Page 참고 바랍니다.
- [ ] 객체지향 프로그래밍에서 컴파일 시점 의존성과 런타임 시점 의존성이 다를 수 있는 이유는 [ ] 때문이다.
- 63 Page 참고 바랍니다.

**Comment by woo00oo** [comment]
1. private, public
2. protected, private
3. **동적 바인딩**
