### ISSUE TITLE
객체의 협력과 역할

### ISSUE THREAD

**Issue by BeomB** [java-pg-study/pg_platforms_study#110]
객체는 특정한 ( 1 ) 에 따라, ( 2 ) 이 바뀔 수 있다. 
동일한 ( 2 ) 을 수행하는 객체들 은 대체 ( 불가능 / 가능 ) 하다.
따라서 다양한 협력이 있더라도 하나의 객체는 ( 하나의 / 다양한 ) 역할을 수행한다.

**Comment by woo00oo** [comment]
협력, 역할, 가능, 다양한
