### ISSUE TITLE
퍼블릭 인터페이스의 품질에 영향을 미치는 원칙과 기법 4가지

### ISSUE THREAD

**Issue by woo00oo** [java-pg-study/pg_platforms_study#134]

**Comment by seoyoungsoo** [comment]
소통해요~

**Comment by Yunjoung808** [comment]
소통해요~

**Comment by woo00oo** [comment]
1. 디미터법칙 -> 객체가 자기 자신을 책임지는 자율적인 존재여야 한다는 사실을 강조한다.
2. 묻지 말고 시켜라 -> 정보 전문가에게 책임을 할당 시킴
3. 의도를 드러내는 인터페이스 -> 네이밍
4. 명령 - 쿼리 분리 원칙
