### ISSUE TITLE
조건문을 대체하는 ( ).

### ISSUE THREAD

**Issue by BeomB** [java-pg-study/pg_platforms_study#139]
객체 지향에서는 조건문을 ( 1 )로 대체한다.

오버라이딩을 이용하여 기존 코드에 영향을 미치지 않고 새로운 객체 유형과 행위를 추가할 수 있는 것을 ( 2 ) 원칙이라한다.

**Comment by woo00oo** [comment]
1. 다형성
2. OCP

객체지향의 5대원칙
1. SRP 단일책임원칙
2. OCP 개방폐쇄원칙
3. LSP 리스코프치환원칙 
4. ISP 인터페이스 분리 원칙
5. DIP 의존관계역전원칙 ddd
