### ISSUE TITLE
디미터 법칙

### ISSUE THREAD

**Issue by BeomB** [java-pg-study/pg_platforms_study#140]
디미터 법칙은 (1)의 방식으로 결합도를 낮춘다. (기차 충돌 방지)
디미터 법칙에 따르면 (2)와 (3) 의 메소드만 호출 가능하다.

**Comment by woo00oo** [comment]
협력 경로를 제한
public class Test {
    private Test2 name;
    List<Test3> name;

   public void test(Test5 test5){
       Test4 test4 = new Test4();
    }

}
