### ISSUE TITLE
대체 가능성을 의미하는 단어

### ISSUE THREAD

**Issue by BeomB** [java-pg-study/pg_platforms_study#55]
동일한 역할을 수행할 수 있는 객체들 사이의 **대체 가능성**을 의미하는 A__는 수신자의 종류를 B__한다.

B_ -> 왕의 "증언하라"라는 메시지를 보내지만 어떤 대상이 수신하는지 알 필요 x

**Comment by woo00oo** [comment]
다형성, 추상화
