### ISSUE TITLE
부록 퀴즈

### ISSUE THREAD

**Issue by BeomB** [java-pg-study/pg_platforms_study#78]
- 범주 사이의 차이를 숨기고 범주간에 공유하는 공통적인 특성을 강조
()

-  객체의 구체적인 세부 사항을 숨기고 인스턴스 간에 공유하는 공통적인 특성을 기반으로 범주를 형성하는 과정
()

- 하나의 개념
()

- 타입을 구현하는 가장 보편적인 방법
()를 이용

[ 일반화, 클래스, 타입, 분류 ]

**Comment by woo00oo** [comment]
1. 일반화
2. 분류
3. 타입
4. 클래스
