### ISSUE TITLE
빈칸 채우기

### ISSUE THREAD

**Issue by Yunjoung808** [java-pg-study/pg_platforms_study#97]
설계를 어렵게 만드는것은  (      )이라는 것을 기억해라
해결 방법은 불필요함 의존성을 제거함으로써 객체사이의 (      )를 낮추는 것이다.
예제에서 결합도를 낮추기 위해 택한 방법은 세부사항을 내부로 감춰 (     )하는것이다.
불필요한 세부사항을 캡슐화하는것은 자율적인 객체들이 낮은 (     )와 높은 (     )를 가지고 협력 하도록 최소한의 의존성만을 남기는것이 훌륭한 객체지향 설계이다.

**Comment by woo00oo** [comment]
의존성, 결합도, 캡슐화, 결합도, 응집도
